export const notificationTypes = {
  JOIN_GROUP_REQUEST: "JOIN_GROUP_REQUEST",
  JOIN_GROUP_REQUEST_ACCEPTED: "JOIN_GROUP_REQUEST_ACCEPTED",
  JOIN_GROUP_REQUEST_REJECTED: "JOIN_GROUP_REQUEST_REJECTED",
  GROUP_MEMBER_ADDED: "GROUP_MEMBER_ADDED",
  GROUP_MEMBER_REMOVED: "GROUP_MEMBER_REMOVED",
  GROUP_MODERATOR_ADDED: "GROUP_MODERATOR_ADDED",
  GROUP_MODERATOR_REMOVED: "GROUP_MODERATOR_REMOVED",
  GROUP_DELETED: "GROUP_DELETED",
  ITEM_ADDED: "ITEM_ADDED",
  ITEM_REMOVED: "ITEM_REMOVED",
  ITEM_EDITED: "ITEM_EDITED",
};

